language: java

jdk:
  - openjdk7

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq zeroc-ice34
    - sudo apt-get install -qq python-imaging python-numpy python-tables

install: python build.py build-all

script: python build.py test-unit-all
