language: java

jdk:
  - openjdk7

sudo: false

matrix:
      fast_finish: true

addons:
  apt_packages:
    - git
    - zeroc-ice34
    - python-imaging
    - python-numpy
    - python-tables
    - python-genshi
    - cmake
    - libgtest-dev

env:
    - BUILD="build-python"
    - BUILD="build-java"

before_install:
    - git config github.token 3bc7fc530b01081559eb911f59ccfec7f4fb2592
    - git config --global user.email snoopycrimecop@gmail.com
    - git config --global user.name 'Snoopy Crime Cop'
    - pip install scc pytest
    - scc travis-merge
    - if [[ $BUILD == 'build-python' ]]; then travis_retry pip install flake8==2.4.0; fi
    - if [[ $BUILD == 'build-python' ]]; then ./components/tools/travis-build py-flake8; fi

# retries the build due to:
# https://github.com/travis-ci/travis-ci/issues/2507
install:
    - if [[ $BUILD == 'build-python' ]]; then travis_retry ./components/tools/travis-build py-build; fi
    - if [[ $BUILD == 'build-java' ]]; then travis_retry ./components/tools/travis-build java-build; fi

script:
    - if [[ $BUILD == 'build-python' ]]; then ./components/tools/travis-build py-test; fi
    - if [[ $BUILD == 'build-java' ]]; then ./components/tools/travis-build java-test; fi
